# Site settings
title:       Muodov's Honey Jar
email:       muodov@gmail.com
author:      Maxim Tsoy
description: "Maxim Tsoy's personal blog"
baseurl:     ""
domain:      "blog.zok.pw"
abouturl:    "https://zok.pw"
url:         "https://blog.zok.pw"
date_format: "%b %-d, %Y"

# Google analytics
google_analytics: UA-66022657-1

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false
show_social_icons:  false
ajaxify_contact_form: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: blogzokpw

# Social icons
github_username: muodov
stackoverflow_id:
twitter_username: muodov
google_plus_id:
linkedin_username: maxtsoy
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: false
share_tumblr: true
share_reddit: true
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
